baseURL: https://brianmsm.github.io/
publishDir: docs
defaultContentLanguage: es
theme: DoIt
title: Brian
enableRobotsTXT: yes
enableGitInfo: yes
enableEmoji: yes
languages:
  es:
    copyright: >
      El contenido de esta p치gina web est치 bajo una 
      [Licencia de Creative Commons Reconocimiento-CompartirIgual 
      4.0 Internacional(CC BY-SA 4.0)]
      (https://creativecommons.org/licenses/by-sa/4.0/es).
    googleAnalytics: ''
    hasCJKLanguage: no
    languageCode: es
    languageName: Espa침ol
    menu:
      main:
        - identifier: posts
          name: Publicaciones
          post: ''
          pre: ''
          title: ''
          url: /posts/
          weight: 1
        - identifier: tags
          name: Etiquetas
          post: ''
          pre: ''
          title: ''
          url: /tags/
          weight: 2
        - identifier: categories
          name: Categor칤as
          post: ''
          pre: ''
          title: ''
          url: /categories/
          weight: 3
        - identifier: series
          name: Series
          post: ''
          pre: ''
          title: ''
          url: /series/
          weight: 4
        - identifier: authors
          name: Autores
          post: ''
          pre: ''
          title: ''
          url: /authors/
          weight: 5
        - identifier: showcase
          name: Showcase
          post: ''
          pre: ''
          title: ''
          url: /showcase/
          weight: 6
        - identifier: documentation
          name: Documentaci칩n
          pre: ''
          title: ''
          url: /categories/documentation/
          weight: 7
        - identifier: about
          name: Sobre m칤
          post: ''
          pre: ''
          title: ''
          url: /about/
          weight: 8
        - identifier: github
          name: ''
          post: ''
          pre: <i class='fab fa-github fa-fw'></i>
          title: GitHub
          url: https://github.com/brianmsm
          weight: 9
    paginate: 12
    params:
      app:
        iconColor: '#5bbad5'
        noFavicon: no
        svgFavicon: ''
        tileColor: '#da532c'
        title: Web Personal de Brian Pe침a Calero
      description: >
        Encontrar치 posts sobre limpieza de datos, estrategias de an치lisis, psicometr칤a,
        universo tidyverse, trucos y recetas con R, tutoriales, benchmarking y m치s 
        cosas interesantes que tuve que aprender leyendo a pedacitos de diversas partes. 
      home:
        posts:
          enable: yes
          paginate: 7
        profile:
          avatarURL: /images/avatar.webp
          disclaimer: ''
          enable: yes
          gravatarEmail: ''
          social: yes
          subtitle: > 
            Aqu칤 encontrar치s informaci칩n sobre investigaci칩n y
            an치lisis de datos
          title: 'Brian Norman Pe침a-Calero'
          typeit: yes
        rss: 10
      keywords:
        - Investigaci칩n
        - An치lisis de datos
        - Psicometr칤a
        - R
        - Tidyverse
        - ggplot2
        - Metodolog칤a
      search:
        absoluteURL: no
        algolia:
          appID: 5YGRNRQK1G
          index: es_index
          searchKey: 0ff6874805de24b84aa1d5ebccad56cd
        contentLength: 4000
        enable: yes
        fuse:
          distance: 100
          findAllMatches: no
          ignoreFieldNorm: no
          ignoreLocation: yes
          isCaseSensitive: no
          location: 0
          minMatchCharLength: 2
          threshold: 0.1
          useExtendedSearch: no
        highlightTag: em
        maxResultLength: 10
        placeholder: ''
        snippetLength: 50
        type: algolia
      social:
        Angellist: ''
        Bandcamp: ''
        Behance: ''
        Bilibili: ''
        Bitbucket: ''
        BuyMeACoffee: ''
        Codepen: ''
        Deviantart: ''
        Devto: ''
        Douban: ''
        Dribbble: ''
        Email: 'brianmsm@gmail.com'
        Facebook: ''
        Fivehundredpx: ''
        Flickr: ''
        Foursquare: ''
        FreeCodeCamp: ''
        GitHub: 'brianmsm'
        Gitea: ''
        Gitlab: ''
        Goodreads: ''
        Googlescholar: 'user=qJ37YioAAAAJ&hl=es'
        Hackernews: ''
        Instagram: ''
        Jsfiddle: ''
        Keybase: ''
        Kickstarter: ''
        Ko-Fi: ''
        Lastfm: ''
        Liberapay: ''
        Linkedin: ''
        Linktree: ''
        Mastodon: ''
        Matrix: ''
        Medium: ''
        Mix: ''
        ORCID: '0000-0002-1073-9306'
        Odnoklassniki: ''
        Patreon: ''
        Paypal: 'brianmsm'
        Pinterest: ''
        QQ: ''
        QQGroup: ''
        Quora: ''
        RSS: yes
        Reddit: ''
        Researchgate: 'Brian-Pena-Calero'
        Skype: ''
        Slidershare: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Stackoverflow: ''
        Steam: ''
        Strava: ''
        Telegram: 'brianpe'
        Thingiverse: ''
        Tumblr: ''
        Twitch: ''
        Twitter: 'brianmsm'
        VK: ''
        Vine: ''
        Weibo: ''
        Whatsapp: ''
        Wordpress: ''
        XMPP: ''
        Xing: ''
        Youtubechannel: 'UC-LGBkFYfXnRWqGfSgu94RA'
        Youtubecustom: ''
        Youtubelegacy: ''
        Zhihu: ''
      sponsor:
        bio: Si quieres contribuir y apoyarme, puedes regalarme un caf칠 游땕.
        enable: no
        link: https://github.com/sponsors/HEIGE-PCloud
    weight: 1
  en:
    copyright: >
      The content of this website is licensed under a [Creative Commons
      Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)]
      (https://creativecommons.org/licenses/by-sa/4.0/)
    googleAnalytics: ''
    hasCJKLanguage: no
    languageCode: en
    languageName: English
    menu:
      main:
        - identifier: posts
          name: Posts
          post: ''
          pre: ''
          title: ''
          url: /posts/
          weight: 1
        - identifier: tags
          name: Tags
          post: ''
          pre: ''
          title: ''
          url: /tags/
          weight: 2
        - identifier: categories
          name: Categories
          post: ''
          pre: ''
          title: ''
          url: /categories/
          weight: 3
        - identifier: series
          name: Series
          post: ''
          pre: ''
          title: ''
          url: /series/
          weight: 4
        - identifier: authors
          name: Authors
          post: ''
          pre: ''
          title: ''
          url: /authors/
          weight: 5
        - identifier: showcase
          name: Showcase
          post: ''
          pre: ''
          title: ''
          url: /showcase/
          weight: 6
        - identifier: documentation
          name: Docs
          post: ''
          pre: ''
          title: ''
          url: /categories/documentation/
          weight: 7
        - identifier: about
          name: About
          post: ''
          pre: ''
          title: ''
          url: /about/
          weight: 8
        - identifier: github
          name: ''
          post: ''
          pre: <i class='fab fa-github fa-fw'></i>
          title: GitHub
          url: https://github.com/brianmsm/
          weight: 9
    paginate: 12
    params:
      app:
        iconColor: '#5bbad5'
        noFavicon: no
        svgFavicon: ''
        tileColor: '#da532c'
        title: Brian Pe침a Calero's Personal Web
      description: >
        You will find posts about data cleaning, analysis strategies, psychometrics,
        tidyverse universe, tricks and recipes with R, tutorials, benchmarking and
        more interesting interesting stuff that I had to learn by reading bits and
        pieces from different parts. 
      home:
        posts:
          enable: yes
          paginate: 7
        profile:
          avatarURL: /images/avatar.webp
          disclaimer: ''
          enable: yes
          gravatarEmail: ''
          social: yes
          subtitle: Here you will find information on research and data analysis
          title: 'Brian Norman Pe침a-Calero'
          typeit: yes
        rss: 10
      keywords:
        - Research
        - Data analysis
        - Psychometrics
        - R
        - Tidyverse
        - ggplot2
        - Methodology
      search:
        absoluteURL: no
        algolia:
          appID: 5YGRNRQK1G
          index: en_index
          searchKey: 0ff6874805de24b84aa1d5ebccad56cd
        contentLength: 4000
        enable: yes
        fuse:
          distance: 100
          findAllMatches: no
          ignoreFieldNorm: no
          ignoreLocation: yes
          isCaseSensitive: no
          location: 0
          minMatchCharLength: 2
          threshold: 0.1
          useExtendedSearch: no
        highlightTag: em
        maxResultLength: 10
        placeholder: ''
        snippetLength: 300
        type: algolia
      social:
        Angellist: ''
        Bandcamp: ''
        Behance: ''
        Bilibili: ''
        Bitbucket: ''
        BuyMeACoffee: ''
        Codepen: ''
        Deviantart: ''
        Devto: ''
        Diaspora: ''
        Douban: ''
        Dribbble: ''
        Email: 'brianmsm@gmail.com'
        Facebook: ''
        Fivehundredpx: ''
        Flickr: ''
        Foursquare: ''
        FreeCodeCamp: ''
        GitHub: 'brianmsm'
        Gitea: ''
        Gitlab: ''
        Goodreads: ''
        Googlescholar: 'user=qJ37YioAAAAJ&hl=es'
        Hackernews: ''
        Instagram: ''
        Jsfiddle: ''
        Keybase: ''
        Kickstarter: ''
        Ko-Fi: ''
        Lastfm: ''
        Liberapay: ''
        Linkedin: ''
        Linktree: ''
        Mastodon: ''
        Matrix: ''
        Medium: ''
        Mix: ''
        ORCID: '0000-0002-1073-9306'
        Odnoklassniki: ''
        Patreon: ''
        Paypal: 'brianmsm'
        Pinterest: ''
        QQ: ''
        QQGroup: ''
        Quora: ''
        RSS: yes
        Reddit: ''
        Researchgate: 'Brian-Pena-Calero'
        Skype: ''
        Slidershare: ''
        Snapchat: ''
        Soundcloud: ''
        Spotify: ''
        Stackoverflow: ''
        Steam: ''
        Strava: ''
        Telegram: 'brianpe'
        Thingiverse: ''
        Tumblr: ''
        Twitch: ''
        Twitter: 'brianmsm'
        VK: ''
        Vine: ''
        Weibo: ''
        Whatsapp: ''
        Wordpress: ''
        XMPP: ''
        Xing: ''
        Youtubechannel: 'UC-LGBkFYfXnRWqGfSgu94RA'
        Youtubecustom: ''
        Youtubelegacy: ''
        Zhihu: ''
      sponsor:
        bio: > 
          If you want to contribute and support me, you can give me a
          coffee as a gift 游땕.
        enable: no
        link: https://github.com/sponsors/HEIGE-PCloud
    weight: 2
params:
  analytics:
    baidu:
      id: ''
    cloudflare:
      token: ''
    enable: no
    fathom:
      id: ''
      server: ''
    google:
      anonymizeIP: yes
      id: ''
    plausible:
      data_domain: ''
      src: ''
    umami:
      data_domains: ''
      data_website_id: ''
      src: ''
  bundle: no
  cdn:
    data: ''
  compatibility:
    objectFit: no
    polyfill: no
  cookieconsent:
    content:
      dismiss: ''
      link: ''
      message: ''
    enable: no
  dateFormat: '2006-01-02'
  defaultTheme: auto
  enablePWA: yes
  fingerprint: ''
  footer:
    author: yes
    copyright: yes
    custom: ''
    enable: yes
    hostedOn: ''
    hugo: yes
    icp: ''
    license: <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-sa/4.0/"
      target="_blank">CC BY-SA 4.0</a>
    since: 2022
  gitRepo: https://github.com/brianmsm
  header:
    desktopMode: fixed
    mobileMode: auto
    themeChangeMode: select
    title:
      logo: ''
      name: Brian
      post: ''
      pre: <i class='far fa-edit fa-fw'></i>
      typeit: yes
  images: /images/avatar.webp
  license: <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-sa/4.0/"
      target="_blank">CC BY-SA 4.0</a>
  list:
    dateFormat: 01-02
    paginate: 20
    rss: 10
  page:
    code:
      copy: yes
      maxShownLines: 10
    comment:
      commento:
        enable: no
      disqus:
        enable: no
        shortname: ''
      enable: yes
      facebook:
        appId: ''
        enable: no
        languageCode: ''
        numPosts: 10
        width: 100%
      giscus:
        darkTheme: dark
        dataCategory: ''
        dataCategoryId: ''
        dataEmitMetadata: '0'
        dataInputPosition: bottom
        dataLang: en
        dataMapping: pathname
        dataReactionsEnabled: '1'
        dataRepo: ''
        dataRepoId: ''
        enable: no
        lightTheme: light
      gitalk:
        clientId: ''
        clientSecret: ''
        enable: no
        owner: ''
        repo: ''
      remark42:
        enable: no
        host: ''
        max_shown_comments: 15
        show_email_subscription: yes
        simple_view: no
        site_id: ''
      telegram:
        color: ''
        colorful: yes
        dark: no
        dislikes: no
        enable: no
        height: ''
        limit: 5
        outlined: no
        siteID: ''
      twikoo:
        commentCount: yes
        enable: no
        envId: ''
        path: ''
        region: ''
        visitor: yes
      utterances:
        darkTheme: github-dark
        enable: no
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        repo: ''
      valine:
        appId: ''
        appKey: ''
        avatar: mp
        emoji: ''
        enable: no
        enableQQ: no
        highlight: yes
        lang: en
        meta: ''
        pageSize: 10
        placeholder: ''
        recordIP: no
        serverURLs: ''
        visitor: yes
      vssue:
        clientId: ''
        clientSecret: ''
        enable: no
        owner: ''
        platform: ''
        repo: ''
      waline:
        commentCount: no
        emoji: https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
        enable: no
        highlight: yes
        login: enable
        mathTagSupport: no
        meta:
          - nick
          - mail
          - link
        pageSize: 10
        requiredMeta: []
        serverURL: https://do-it-waline-comment.vercel.app/
        uploadImage: no
        visitor: no
        wordLimit: 0
    fontawesome: yes
    fraction: yes
    header:
      number:
        enable: yes
        format:
          h2: '{h2} {title}'
          h3: '{h2}.{h3} {title}'
          h4: '{h2}.{h3}.{h4} {title}'
          h5: '{h2}.{h3}.{h4}.{h5} {title}'
          h6: '{h2}.{h3}.{h4}.{h5}.{h6} {title}'
    hiddenFromHomePage: no
    hiddenFromSearch: no
    library:
      css: {}
      js: {}
    lightgallery: no
    linkToEdit: https://github.com/brianmsm/brianmsm.github.io/edit/main/content/{path}
    linkToMarkdown: yes
    linkToReport: https://github.com/brianmsm/brianmsm.github.io/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/brianmsm/brianmsm.github.io/blob/main/content/{path}|
    linkToSource: https://github.com/brianmsm/brianmsm.github.io/blob/main/content/{path}
    mapbox:
      accessToken: pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ
      darkStyle: mapbox://styles/mapbox/dark-v10?optimize=true
      fullscreen: yes
      geolocate: yes
      lightStyle: mapbox://styles/mapbox/light-v10?optimize=true
      navigation: yes
      scale: yes
    math:
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      copyTex: yes
      enable: no
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      mhchem: yes
    outdatedArticleReminder:
      enable: no
      reminder: 90
      warning: 180
    pageStyle: normal
    rssFullText: no
    ruby: yes
    seo:
      images: []
      publisher:
        logoUrl: /images/avatar.webp
        name: xxxx
    seriesNavigation: yes
    share:
      Baidu: no
      Blogger: no
      Buffer: no
      Digg: no
      Evernote: no
      Facebook: yes
      Flipboard: no
      HackerNews: no
      Instapaper: no
      Line: yes
      Linkedin: yes
      Mix: no
      Myspace: no
      Odnoklassniki: no
      Pinterest: no
      Pocket: no
      Reddit: no
      Renren: no
      Skype: no
      Stumbleupon: no
      Telegram: yes
      Trello: no
      Tumblr: no
      Twitter: yes
      VK: no
      Weibo: yes
      Whatsapp: yes
      Xing: no
      enable: yes
    table:
      sort: yes
    toc:
      auto: yes
      enable: yes
      keepStatic: no
    twemoji: no
  section:
    dateFormat: 01-02
    paginate: 20
    recentlyUpdated:
      days: 30
      enable: yes
      maxCount: 10
      rss: yes
    rss: 10
  seo:
    image: /images/Apple-Devices-Preview.png
    thumbnailUrl: /images/screenshot.png
  sponsor:
    bio: If you find this post helpful, please consider sponsoring.
    enable: no
    link: https://github.com/sponsors/HEIGE-PCloud
  title: Web Personal de Brian Pe침a Calero
  typeit:
    cursorChar: '|'
    cursorSpeed: 1000
    duration: -1
    speed: 100
  verification:
    baidu: ''
    bing: ''
    google: ''
    pinterest: ''
    so: ''
    sogou: ''
    yandex: ''
  version: 0.2.X
markup:
  goldmark:
    extensions:
      definitionList: yes
      footnote: yes
      linkify: yes
      strikethrough: yes
      table: yes
      taskList: yes
      typographer: yes
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes
    guessSyntax: yes
    lineNos: yes
    lineNumbersInTable: yes
    noClasses: no
  tableOfContents:
    endLevel: 6
    startLevel: 2
author:
  avatar: /images/avatar.webp
  email: 'brianmsm@gmail.com'
  gravatarEmail: ''
  link: https://github.com/brianmsm
  name: Brian Norman Pe침a Calero
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :filename
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: yes
  youtube:
    privacyEnhanced: yes
mediaTypes:
  text/plain:
    suffixes: md
outputFormats:
  MarkDown:
    isHTML: no
    isPlainText: yes
    mediaType: text/plain
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm: HTML
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
